### ISSUE TITLE
Add feature detection for ResizeObserver

### ISSUE THREAD

**Issue by hirasso** [aerni/alpine-resize#2]
Hi again! I just had a thought: Shouldn't this directive probably do some feature detection before initializing the `ResizeObserver`? That way it would stay "progressive enhancement" and wouldn't break sites on older browsers. Anything like this:

```js
if (typeof window.ResizeObserver !== 'function') return
```
or 
```js
if (!"ResizeObserver" in window) return;
```

**Comment by aerni** [comment]
I don't think this is necessary, as Alpine.js requires even newer browsers than this plugin.
